[package]
name = "ota"
version = "0.1.0"
authors = ["John Barker <jebarker@gmail.com>"]

[features]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]
