[package]
name = "ota"
version = "0.1.0"
authors = ["John Barker <jebarker@gmail.com>"]

[features]

[dependencies]
handlebars = "1.0"
regex = "1.0.1"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.3.6"
default-features = false
features = ["handlebars_templates", "json"]

[dependencies.chrono]
version = "0.4"
features = ["serde", "rustc-serialize"]
